"""Add description to MeetingRoom

Revision ID: 49540d0fc84f
Revises: 2f9884af4976
Create Date: 2023-12-22 11:37:43.463081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49540d0fc84f'
down_revision = '2f9884af4976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
